### ISSUE TITLE
Ensure in the build_demo command that the server is running

### ISSUE THREAD

**Issue by ArthurPBressan** [mining/mining#257]
Due to the huge amount of SQLite commands, the INSERTs takes a good while to complete, and only after that runs, I receive an error that the server had to be running to insert the admin user.

One option is to add a GET to the home page (or wherever) before the INSERT or make it clear in the "Running Demo" section of the README that the server has to be running before running the build_demo command. As that section stands now, it's very easy to think that the runserver command is executed after the build command.

**Comment by lerrua** [comment]
Yep, it's a bug on our documentation. The build_demo command uses the OpenMining server api to build some things.
