### ISSUE TITLE
MS Sql server not connect

### ISSUE THREAD

**Issue by abuvanth** [mining/mining#276]
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mssql/pymssql.py", line 72, in _get_server_version_info
    r"Microsoft SQL Server.*? - (\d+).(\d+).(\d+).(\d+)", vers)
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

**Comment by abuvanth** [comment]
getting this error while creating db engine using pysqlalchemy in python 2.7

but in python3 works well... but open mining runs only in python 2.7 so ms sql server not connect with open mining

**Comment by avelino** [comment]
@abuvanth can you contribute to the project by sending this correction?

**Comment by abuvanth** [comment]
easy_install --upgrade pymssql
